<?php

/**
 * Utilities class
 *
 * @package    Freesound
 * @subpackage Freesound_Utils
 */
class Freesound_Utils
{
	public static function BundleBuild( $file )
	{
		if (is_file( $file )) {
			throw new Exception( "File '$file' already exists, please remove it before trying to build a new bundle" );
		}

		$basepath = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR;
		$classpaths = array_unique( array_values( Freesound_Bootstrap::$classmap ) );

		$content = "<?php\n\n";
		$content .= "/***********************************************************\n";
		$content .= " *\n";
		$content .= " * DO NOT EDIT THIS FILE!!\n";
		$content .= " * This file was automatically generated by PHP.\n";
		$content .= " *\n";
		$content .= " * Generated at: " . date( 'r' ) . "\n";
		$content .= " *\n";
		$content .= " ***********************************************************/\n";
		$content .= "define( '__FREESOUND_BUNDLE__', true );\n\n";

		foreach( $classpaths as $path ) {
			$f = $basepath . $path . Freesound_Bootstrap::CLASS_EXTENSION;
			if (false === ($c = @file_get_contents( $f ))) {
				throw new Exception( "Could not open file '$f'" );
			}
			// remove php tags
			$c = preg_replace( array( '#<\?(?:php)?\s*#s', '#\?\>(?=([\s\n]+)?$(?!\n))#s' ), null, $c );
			$content .= "$c\n\n";
		}

		$content .= "?>";

		return @file_put_contents( $file, $content ) !== false;
	}
}

?>
